module.exports = {
 classes:  { 
  aerialway: null,
  aeroway: null,
  amenity: null,
  area: null,
  barrier: null,
  bicycle: null,
  brand: null,
  bridge: null,
  boundary: null,
  building: null,
  capital: null,
  construction: null,
  covered: null,
  culvert: null,
  cutting: null,
  denomination: null,
  disused: null,
  ele: null,
  embankment: null,
  foot: null,
  'generator:source': null,
  harbour: null,
  highway: null,
  historic: null,
  horse: null,
  intermittent: null,
  junction: null,
  landuse: null,
  layer: null,
  leisure: null,
  lock: null,
  man_made: null,
  military: null,
  motorcar: null,
  natural: null,
  oneway: null,
  operator: null,
  poi: null,
  population: null,
  power: null,
  power_source: null,
  place: null,
  railway: null,
  ref: null,
  religion: null,
  route: null,
  service: null,
  shop: null,
  sport: null,
  surface: null,
  toll: null,
  tourism: null,
  'tower:type': null,
  tunnel: null,
  water: null,
  waterway: null,
  wetland: null,
  width: null,
  wood: null,
},
 

  get: function (row) {
var classes = Array();
 var attr = { 
  aerialway: null,
  aeroway: null,
  amenity: null,
  area: null,
  barrier: null,
  bicycle: null,
  brand: null,
  bridge: null,
  boundary: null,
  building: null,
  capital: null,
  construction: null,
  covered: null,
  culvert: null,
  cutting: null,
  denomination: null,
  disused: null,
  ele: null,
  embankment: null,
  foot: null,
  'generator:source': null,
  harbour: null,
  highway: null,
  historic: null,
  horse: null,
  intermittent: null,
  junction: null,
  landuse: null,
  layer: null,
  leisure: null,
  lock: null,
  man_made: null,
  military: null,
  motorcar: null,
  natural: null,
  oneway: null,
  operator: null,
  poi: null,
  population: null,
  power: null,
  power_source: null,
  place: null,
  railway: null,
  ref: null,
  religion: null,
  route: null,
  service: null,
  shop: null,
  sport: null,
  surface: null,
  toll: null,
  tourism: null,
  'tower:type': null,
  tunnel: null,
  water: null,
  waterway: null,
  wetland: null,
  width: null,
  wood: null,
};
for(var prop in attr) {
    if(row.hasOwnProperty(prop)){
    if(row[prop]!=null){
    	classes.push(row[prop]);
	}
    }
}
return classes;

	},
  interactions: function () {
 var amenity = { 
police:null,
bicycle_parking:null,
mall:null,
car_rental:null,
townhall:null,
courthouse:null,
cinema:null,
fountain:null,
compressed_air:null,
grave_yard:null,
library:null,
school:null,
kindergarten:null,
studio:null,
payment_center:null,
pub:null,
atm:null,
parking:null,
salon_de_belleza:null,
restaurant:null,
bar:null,
car_wash:null,
cafe:null,
Las_Lanzas:null,
place_of_worship:null,
fuel:null,
marketplace:null,
ice_cream:null,
internet_access:null,
lift_gate:null,
veterinary:null,
nightclub:null,
university:null,
clock:null,
telephone:null,
drinking_water:null,
hospital:null,
waste_basket:null,
swimming_pool:null,
emergency_phone:null,
fast_food:null,
post_box:null,
vending_machine:null,
bureau_de_change:null,
dentist:null,
public_building:null,
bank:null,
bus_station:null,
bbq:null,
post_office:null,
fire_hydrant:null,
community_centre:null,
doctors:null,
prison:null,
clubhouse:null,
pharmacy:null,
recycling:null,
bench:null,
arts_centre:null,
embassy:null,
taxi:null,
bicycle_rental:null,
toilets:null,
waste_transfer_station:null,
gym:null,
shelter:null,
college:null,
theatre:null,
fire_station:null
}
var list = {
people:null,
deer:null,
crimes:null,
animal:null
};

for(var prop in list) {
list[prop] = Array();
for(var prop2 in amenity) {
    	list[prop].push({prop2: 1});
	}
}





return list;

	}


};

